// Python 코드카타 문제 목록 (총 441개)
// difficulty: 0 (L0 기초·입문), 1-5 (L1~L5), 7 (레벨7 챌린지), 8 (레벨8 백준)
const PROBLEMS = [
  // ========== 프로그래머스 (1-180) ==========

  // L1 입문 (1-12)
  { id: 1, difficulty: 1, title: "두 수의 차", platform: "programmers", problemId: "120803", algorithm: "기본연산" },
  { id: 2, difficulty: 1, title: "두 수의 곱", platform: "programmers", problemId: "120804", algorithm: "기본연산" },
  { id: 3, difficulty: 1, title: "몫 구하기", platform: "programmers", problemId: "120805", algorithm: "기본연산" },
  { id: 4, difficulty: 1, title: "나이 출력", platform: "programmers", problemId: "120820", algorithm: "기본연산" },
  { id: 5, difficulty: 1, title: "숫자 비교하기", platform: "programmers", problemId: "120807", algorithm: "기본연산, 조건문" },
  { id: 6, difficulty: 1, title: "두 수의 합", platform: "programmers", problemId: "120802", algorithm: "기본연산" },
  { id: 7, difficulty: 1, title: "두 수의 나눗셈", platform: "programmers", problemId: "120806", algorithm: "기본연산" },
  { id: 8, difficulty: 1, title: "각도기", platform: "programmers", problemId: "120829", algorithm: "기본연산, 조건문" },
  { id: 9, difficulty: 1, title: "짝수의 합", platform: "programmers", problemId: "120831", algorithm: "반복문, 조건문" },
  { id: 10, difficulty: 1, title: "배열의 평균값", platform: "programmers", problemId: "120817", algorithm: "기본연산, 배열" },
  { id: 11, difficulty: 1, title: "짝수와 홀수", platform: "programmers", problemId: "12937", algorithm: "기본연산, 조건문" },
  { id: 12, difficulty: 1, title: "평균 구하기", platform: "programmers", problemId: "12944", algorithm: "기본연산, 배열" },

  // L2 기초 (13-41) - 일부 L1 포함
  { id: 13, difficulty: 2, title: "자릿수 더하기", platform: "programmers", problemId: "12931", algorithm: "문자열, 반복문" },
  { id: 14, difficulty: 2, title: "약수의 합", platform: "programmers", problemId: "12928", algorithm: "수학, 반복문" },
  { id: 15, difficulty: 2, title: "나머지가 1이 되는 수 찾기", platform: "programmers", problemId: "87389", algorithm: "수학, 반복문" },
  { id: 16, difficulty: 2, title: "x만큼 간격이 있는 n개의 숫자", platform: "programmers", problemId: "12954", algorithm: "배열" },
  { id: 17, difficulty: 2, title: "자연수 뒤집어 배열로 만들기", platform: "programmers", problemId: "12932", algorithm: "문자열, 배열" },
  { id: 18, difficulty: 1, title: "문자열을 정수로 바꾸기", platform: "programmers", problemId: "12925", algorithm: "기본연산, 형변환" },
  { id: 19, difficulty: 2, title: "정수 제곱근 판별", platform: "programmers", problemId: "12934", algorithm: "수학" },
  { id: 20, difficulty: 2, title: "정수 내림차순으로 배치하기", platform: "programmers", problemId: "12933", algorithm: "문자열, 정렬" },
  { id: 21, difficulty: 2, title: "하샤드 수", platform: "programmers", problemId: "12947", algorithm: "수학, 문자열" },
  { id: 22, difficulty: 2, title: "두 정수 사이의 합", platform: "programmers", problemId: "12912", algorithm: "수학" },
  { id: 23, difficulty: 2, title: "콜라츠 추측", platform: "programmers", problemId: "12943", algorithm: "시뮬레이션, 반복문" },
  { id: 24, difficulty: 1, title: "서울에서 김서방 찾기", platform: "programmers", problemId: "12919", algorithm: "배열, 탐색" },
  { id: 25, difficulty: 2, title: "나누어 떨어지는 숫자 배열", platform: "programmers", problemId: "12910", algorithm: "배열, 정렬" },
  { id: 26, difficulty: 2, title: "음양 더하기", platform: "programmers", problemId: "76501", algorithm: "배열" },
  { id: 27, difficulty: 2, title: "핸드폰 번호 가리기", platform: "programmers", problemId: "12948", algorithm: "문자열" },
  { id: 28, difficulty: 2, title: "없는 숫자 더하기", platform: "programmers", problemId: "86051", algorithm: "배열, 해시" },
  { id: 29, difficulty: 2, title: "제일 작은 수 제거하기", platform: "programmers", problemId: "12935", algorithm: "배열" },
  { id: 30, difficulty: 1, title: "가운데 글자 가져오기", platform: "programmers", problemId: "12903", algorithm: "문자열" },
  { id: 31, difficulty: 2, title: "수박수박수박수박수박수?", platform: "programmers", problemId: "12922", algorithm: "문자열" },
  { id: 32, difficulty: 2, title: "내적", platform: "programmers", problemId: "70128", algorithm: "배열, 수학" },
  { id: 33, difficulty: 2, title: "약수의 개수와 덧셈", platform: "programmers", problemId: "77884", algorithm: "수학" },
  { id: 34, difficulty: 2, title: "문자열 내림차순으로 배치하기", platform: "programmers", problemId: "12917", algorithm: "문자열, 정렬" },
  { id: 35, difficulty: 2, title: "부족한 금액 계산하기", platform: "programmers", problemId: "82612", algorithm: "수학" },
  { id: 36, difficulty: 2, title: "문자열 다루기 기본", platform: "programmers", problemId: "12918", algorithm: "문자열" },
  { id: 37, difficulty: 2, title: "행렬의 덧셈", platform: "programmers", problemId: "12950", algorithm: "배열" },
  { id: 38, difficulty: 1, title: "직사각형 별찍기", platform: "programmers", problemId: "12969", algorithm: "반복문" },
  { id: 39, difficulty: 2, title: "최대공약수와 최소공배수", platform: "programmers", problemId: "12940", algorithm: "수학" },
  { id: 40, difficulty: 2, title: "3진법 뒤집기", platform: "programmers", problemId: "68935", algorithm: "수학, 문자열" },
  { id: 41, difficulty: 2, title: "이상한 문자 만들기", platform: "programmers", problemId: "12930", algorithm: "문자열" },

  // L3 중급 (42-83)
  { id: 42, difficulty: 3, title: "삼총사", platform: "programmers", problemId: "131705", algorithm: "완전탐색" },
  { id: 43, difficulty: 2, title: "크기가 작은 부분문자열", platform: "programmers", problemId: "147355", algorithm: "문자열" },
  { id: 44, difficulty: 3, title: "최소직사각형", platform: "programmers", problemId: "86491", algorithm: "완전탐색, 그리디" },
  { id: 45, difficulty: 2, title: "시저 암호", platform: "programmers", problemId: "12926", algorithm: "문자열" },
  { id: 46, difficulty: 2, title: "숫자 문자열과 영단어", platform: "programmers", problemId: "81301", algorithm: "문자열, 해시" },
  { id: 47, difficulty: 2, title: "문자열 내 마음대로 정렬하기", platform: "programmers", problemId: "12915", algorithm: "정렬" },
  { id: 48, difficulty: 2, title: "K번째수", platform: "programmers", problemId: "42748", algorithm: "정렬" },
  { id: 49, difficulty: 3, title: "두 개 뽑아서 더하기", platform: "programmers", problemId: "68644", algorithm: "완전탐색" },
  { id: 50, difficulty: 2, title: "가장 가까운 같은 글자", platform: "programmers", problemId: "142086", algorithm: "해시" },
  { id: 51, difficulty: 2, title: "푸드 파이트 대회", platform: "programmers", problemId: "134240", algorithm: "문자열" },
  { id: 52, difficulty: 2, title: "콜라 문제", platform: "programmers", problemId: "132267", algorithm: "시뮬레이션" },
  { id: 53, difficulty: 3, title: "명예의 전당 (1)", platform: "programmers", problemId: "138477", algorithm: "정렬, 힙" },
  { id: 54, difficulty: 2, title: "2016년", platform: "programmers", problemId: "12901", algorithm: "수학" },
  { id: 55, difficulty: 3, title: "카드 뭉치", platform: "programmers", problemId: "159994", algorithm: "스택/큐" },
  { id: 56, difficulty: 2, title: "과일 장수", platform: "programmers", problemId: "135808", algorithm: "정렬, 그리디" },
  { id: 57, difficulty: 3, title: "모의고사", platform: "programmers", problemId: "42840", algorithm: "완전탐색" },
  { id: 58, difficulty: 3, title: "소수 만들기", platform: "programmers", problemId: "12977", algorithm: "완전탐색, 수학" },
  { id: 59, difficulty: 3, title: "덧칠하기", platform: "programmers", problemId: "161989", algorithm: "그리디" },
  { id: 60, difficulty: 2, title: "기사단원의 무기", platform: "programmers", problemId: "136798", algorithm: "수학" },
  { id: 61, difficulty: 2, title: "로또의 최고 순위와 최저 순위", platform: "programmers", problemId: "77484", algorithm: "해시" },
  { id: 62, difficulty: 3, title: "옹알이 (2)", platform: "programmers", problemId: "133499", algorithm: "문자열" },
  { id: 63, difficulty: 3, title: "숫자 짝꿍", platform: "programmers", problemId: "131128", algorithm: "해시, 문자열" },
  { id: 64, difficulty: 3, title: "체육복", platform: "programmers", problemId: "42862", algorithm: "그리디" },
  { id: 65, difficulty: 2, title: "문자열 나누기", platform: "programmers", problemId: "140108", algorithm: "문자열, 시뮬레이션" },
  { id: 66, difficulty: 3, title: "대충 만든 자판", platform: "programmers", problemId: "160586", algorithm: "해시" },
  { id: 67, difficulty: 2, title: "둘만의 암호", platform: "programmers", problemId: "155652", algorithm: "문자열" },
  { id: 68, difficulty: 3, title: "햄버거 만들기", platform: "programmers", problemId: "133502", algorithm: "스택" },
  { id: 69, difficulty: 3, title: "성격 유형 검사하기", platform: "programmers", problemId: "118666", algorithm: "해시, 시뮬레이션" },
  { id: 70, difficulty: 2, title: "바탕화면 정리", platform: "programmers", problemId: "161990", algorithm: "시뮬레이션" },
  { id: 71, difficulty: 3, title: "개인정보 수집 유효기간", platform: "programmers", problemId: "150370", algorithm: "시뮬레이션, 문자열" },
  { id: 72, difficulty: 3, title: "달리기 경주", platform: "programmers", problemId: "178871", algorithm: "해시" },
  { id: 73, difficulty: 2, title: "공원 산책", platform: "programmers", problemId: "172928", algorithm: "시뮬레이션" },
  { id: 74, difficulty: 3, title: "신고 결과 받기", platform: "programmers", problemId: "92334", algorithm: "해시, 시뮬레이션" },
  { id: 75, difficulty: 2, title: "최댓값과 최솟값", platform: "programmers", problemId: "12939", algorithm: "문자열" },
  { id: 76, difficulty: 2, title: "JadenCase 문자열 만들기", platform: "programmers", problemId: "12951", algorithm: "문자열" },
  { id: 77, difficulty: 3, title: "이진 변환 반복하기", platform: "programmers", problemId: "70129", algorithm: "시뮬레이션, 문자열" },
  { id: 78, difficulty: 3, title: "피보나치 수", platform: "programmers", problemId: "12945", algorithm: "DP" },
  { id: 79, difficulty: 3, title: "카펫", platform: "programmers", problemId: "42842", algorithm: "완전탐색, 수학" },
  { id: 80, difficulty: 3, title: "예상 대진표", platform: "programmers", problemId: "12985", algorithm: "시뮬레이션" },
  { id: 81, difficulty: 3, title: "N개의 최소공배수", platform: "programmers", problemId: "12953", algorithm: "수학" },
  { id: 82, difficulty: 3, title: "멀리 뛰기", platform: "programmers", problemId: "12914", algorithm: "DP" },
  { id: 83, difficulty: 3, title: "귤 고르기", platform: "programmers", problemId: "138476", algorithm: "해시, 그리디" },

  // L4 중상 (84-143)
  { id: 84, difficulty: 4, title: "괄호 회전하기", platform: "programmers", problemId: "76502", algorithm: "스택, 문자열" },
  { id: 85, difficulty: 3, title: "연속 부분 수열 합의 개수", platform: "programmers", problemId: "131701", algorithm: "해시, 슬라이딩윈도우" },
  { id: 86, difficulty: 3, title: "H-Index", platform: "programmers", problemId: "42747", algorithm: "정렬" },
  { id: 87, difficulty: 3, title: "n^2 배열 자르기", platform: "programmers", problemId: "87390", algorithm: "수학, 시뮬레이션" },
  { id: 88, difficulty: 3, title: "행렬의 곱셈", platform: "programmers", problemId: "12949", algorithm: "배열" },
  { id: 89, difficulty: 3, title: "할인 행사", platform: "programmers", problemId: "131127", algorithm: "해시, 슬라이딩윈도우" },
  { id: 90, difficulty: 3, title: "의상", platform: "programmers", problemId: "42578", algorithm: "해시, 수학" },
  { id: 91, difficulty: 3, title: "기능개발", platform: "programmers", problemId: "42586", algorithm: "스택/큐" },
  { id: 92, difficulty: 3, title: "프로세스", platform: "programmers", problemId: "42587", algorithm: "스택/큐" },
  { id: 93, difficulty: 4, title: "피로도", platform: "programmers", problemId: "87946", algorithm: "완전탐색, 백트래킹" },
  { id: 94, difficulty: 4, title: "타겟 넘버", platform: "programmers", problemId: "43165", algorithm: "DFS, 완전탐색" },
  { id: 95, difficulty: 3, title: "k진수에서 소수 개수 구하기", platform: "programmers", problemId: "92335", algorithm: "수학, 문자열" },
  { id: 96, difficulty: 3, title: "주차 요금 계산", platform: "programmers", problemId: "92341", algorithm: "해시, 시뮬레이션" },
  { id: 97, difficulty: 3, title: "모음사전", platform: "programmers", problemId: "84512", algorithm: "완전탐색" },
  { id: 98, difficulty: 4, title: "뒤에 있는 큰 수 찾기", platform: "programmers", problemId: "154539", algorithm: "스택" },
  { id: 99, difficulty: 3, title: "롤케이크 자르기", platform: "programmers", problemId: "132265", algorithm: "해시" },
  { id: 100, difficulty: 4, title: "숫자 변환하기", platform: "programmers", problemId: "154538", algorithm: "BFS, DP" },
  { id: 101, difficulty: 4, title: "2개 이하로 다른 비트", platform: "programmers", problemId: "77885", algorithm: "비트연산" },
  { id: 102, difficulty: 4, title: "다리를 지나는 트럭", platform: "programmers", problemId: "42583", algorithm: "스택/큐, 시뮬레이션" },
  { id: 103, difficulty: 4, title: "가장 큰 수", platform: "programmers", problemId: "42746", algorithm: "정렬" },
  { id: 104, difficulty: 4, title: "소수 찾기", platform: "programmers", problemId: "42839", algorithm: "완전탐색, 수학" },
  { id: 105, difficulty: 4, title: "쿼드압축 후 개수 세기", platform: "programmers", problemId: "68936", algorithm: "분할정복" },
  { id: 106, difficulty: 4, title: "택배상자", platform: "programmers", problemId: "131704", algorithm: "스택" },
  { id: 107, difficulty: 4, title: "큰 수 만들기", platform: "programmers", problemId: "42883", algorithm: "그리디, 스택" },
  { id: 108, difficulty: 4, title: "삼각 달팽이", platform: "programmers", problemId: "68645", algorithm: "시뮬레이션" },
  { id: 109, difficulty: 4, title: "연속된 부분 수열의 합", platform: "programmers", problemId: "178870", algorithm: "투포인터" },
  { id: 110, difficulty: 4, title: "두 큐 합 같게 만들기", platform: "programmers", problemId: "118667", algorithm: "큐, 투포인터" },
  { id: 111, difficulty: 4, title: "무인도 여행", platform: "programmers", problemId: "154540", algorithm: "DFS/BFS" },
  { id: 112, difficulty: 4, title: "행렬 테두리 회전하기", platform: "programmers", problemId: "77485", algorithm: "시뮬레이션" },
  { id: 113, difficulty: 4, title: "전력망을 둘로 나누기", platform: "programmers", problemId: "86971", algorithm: "DFS/BFS, 그래프" },
  { id: 114, difficulty: 5, title: "배달", platform: "programmers", problemId: "12978", algorithm: "그래프, 다익스트라" },
  { id: 115, difficulty: 4, title: "호텔 대실", platform: "programmers", problemId: "155651", algorithm: "정렬, 그리디" },
  { id: 116, difficulty: 4, title: "점 찍기", platform: "programmers", problemId: "140107", algorithm: "수학" },
  { id: 117, difficulty: 4, title: "마법의 엘리베이터", platform: "programmers", problemId: "148653", algorithm: "그리디" },
  { id: 118, difficulty: 4, title: "거리두기 확인하기", platform: "programmers", problemId: "81302", algorithm: "BFS, 시뮬레이션" },
  { id: 119, difficulty: 4, title: "숫자 카드 나누기", platform: "programmers", problemId: "135807", algorithm: "수학, GCD" },
  { id: 120, difficulty: 4, title: "멀쩡한 사각형", platform: "programmers", problemId: "62048", algorithm: "수학, GCD" },
  { id: 121, difficulty: 4, title: "시소 짝꿍", platform: "programmers", problemId: "152996", algorithm: "해시, 수학" },
  { id: 122, difficulty: 4, title: "테이블 해시 함수", platform: "programmers", problemId: "147354", algorithm: "정렬, 해시" },
  { id: 123, difficulty: 5, title: "하노이의 탑", platform: "programmers", problemId: "12946", algorithm: "재귀, 분할정복" },
  { id: 124, difficulty: 4, title: "미로 탈출", platform: "programmers", problemId: "159993", algorithm: "BFS" },
  { id: 125, difficulty: 4, title: "혼자 놀기의 달인", platform: "programmers", problemId: "131130", algorithm: "그래프, 시뮬레이션" },
  { id: 126, difficulty: 4, title: "광물 캐기", platform: "programmers", problemId: "172927", algorithm: "그리디, 완전탐색" },
  { id: 127, difficulty: 5, title: "리코쳇 로봇", platform: "programmers", problemId: "169199", algorithm: "BFS" },
  { id: 128, difficulty: 4, title: "디펜스 게임", platform: "programmers", problemId: "142085", algorithm: "힙, 그리디" },
  { id: 129, difficulty: 4, title: "우박수열 정적분", platform: "programmers", problemId: "134239", algorithm: "수학, 시뮬레이션" },
  { id: 130, difficulty: 4, title: "두 원 사이의 정수 쌍", platform: "programmers", problemId: "181187", algorithm: "수학" },
  { id: 131, difficulty: 5, title: "N-Queen", platform: "programmers", problemId: "12952", algorithm: "백트래킹" },
  { id: 132, difficulty: 4, title: "과제 진행하기", platform: "programmers", problemId: "176962", algorithm: "스택, 시뮬레이션" },
  { id: 133, difficulty: 5, title: "조이스틱", platform: "programmers", problemId: "42860", algorithm: "그리디" },
  { id: 134, difficulty: 4, title: "혼자서 하는 틱택토", platform: "programmers", problemId: "160585", algorithm: "시뮬레이션" },
  { id: 135, difficulty: 5, title: "이모티콘 할인행사", platform: "programmers", problemId: "150368", algorithm: "완전탐색" },
  { id: 136, difficulty: 4, title: "요격 시스템", platform: "programmers", problemId: "181188", algorithm: "그리디, 정렬" },
  { id: 137, difficulty: 5, title: "양궁 대회", platform: "programmers", problemId: "92342", algorithm: "완전탐색, 그리디" },
  { id: 138, difficulty: 4, title: "교점에 별 만들기", platform: "programmers", problemId: "87377", algorithm: "수학" },
  { id: 139, difficulty: 5, title: "택배 배달과 수거하기", platform: "programmers", problemId: "150369", algorithm: "그리디" },
  { id: 140, difficulty: 5, title: "유사 칸토어 비트열", platform: "programmers", problemId: "148652", algorithm: "분할정복" },
  { id: 141, difficulty: 4, title: "당구 연습", platform: "programmers", problemId: "169198", algorithm: "수학" },
  { id: 142, difficulty: 5, title: "빛의 경로 사이클", platform: "programmers", problemId: "86052", algorithm: "시뮬레이션, 그래프" },
  { id: 143, difficulty: 4, title: "이중우선순위큐", platform: "programmers", problemId: "42628", algorithm: "힙" },

  // L5 고급 (144-160)
  { id: 144, difficulty: 4, title: "네트워크", platform: "programmers", problemId: "43162", algorithm: "DFS/BFS" },
  { id: 145, difficulty: 5, title: "단어 변환", platform: "programmers", problemId: "43163", algorithm: "DFS/BFS" },
  { id: 146, difficulty: 4, title: "베스트앨범", platform: "programmers", problemId: "42579", algorithm: "해시, 정렬" },
  { id: 147, difficulty: 5, title: "가장 먼 노드", platform: "programmers", problemId: "49189", algorithm: "그래프, BFS" },
  { id: 148, difficulty: 5, title: "섬 연결하기", platform: "programmers", problemId: "42861", algorithm: "그래프, MST" },
  { id: 149, difficulty: 5, title: "여행경로", platform: "programmers", problemId: "43164", algorithm: "DFS, 그래프" },
  { id: 150, difficulty: 5, title: "디스크 컨트롤러", platform: "programmers", problemId: "42627", algorithm: "힙, 스케줄링" },
  { id: 151, difficulty: 5, title: "입국심사", platform: "programmers", problemId: "43238", algorithm: "이진탐색" },
  { id: 152, difficulty: 5, title: "가장 긴 팰린드롬", platform: "programmers", problemId: "12904", algorithm: "DP, 문자열" },
  { id: 153, difficulty: 5, title: "연속 펄스 부분 수열의 합", platform: "programmers", problemId: "161988", algorithm: "DP" },
  { id: 154, difficulty: 5, title: "풍선 터트리기", platform: "programmers", problemId: "68646", algorithm: "시뮬레이션" },
  { id: 155, difficulty: 5, title: "다단계 칫솔 판매", platform: "programmers", problemId: "77486", algorithm: "트리, DFS" },
  { id: 156, difficulty: 5, title: "순위", platform: "programmers", problemId: "49191", algorithm: "그래프, 플로이드워셜" },
  { id: 157, difficulty: 5, title: "부대복귀", platform: "programmers", problemId: "132266", algorithm: "BFS, 그래프" },
  { id: 158, difficulty: 5, title: "인사고과", platform: "programmers", problemId: "152995", algorithm: "정렬" },
  { id: 159, difficulty: 5, title: "양과 늑대", platform: "programmers", problemId: "92343", algorithm: "DFS, 비트마스킹" },
  { id: 160, difficulty: 5, title: "110 옮기기", platform: "programmers", problemId: "77886", algorithm: "문자열, 스택" },

  // 레벨7 챌린지 (161-180)
  { id: 161, difficulty: 7, title: "미로 탈출 명령어", platform: "programmers", problemId: "150365", algorithm: "DFS, 문자열" },
  { id: 162, difficulty: 7, title: "표현 가능한 이진트리", platform: "programmers", problemId: "150367", algorithm: "분할정복, 트리" },
  { id: 163, difficulty: 7, title: "스타 수열", platform: "programmers", problemId: "70130", algorithm: "해시" },
  { id: 164, difficulty: 7, title: "N으로 표현", platform: "programmers", problemId: "42895", algorithm: "DP" },
  { id: 165, difficulty: 7, title: "등산코스 정하기", platform: "programmers", problemId: "118669", algorithm: "그래프, 다익스트라" },
  { id: 166, difficulty: 7, title: "모두 0으로 만들기", platform: "programmers", problemId: "76503", algorithm: "DFS, 트리" },
  { id: 167, difficulty: 7, title: "표 병합", platform: "programmers", problemId: "150366", algorithm: "Union-Find, 시뮬레이션" },
  { id: 168, difficulty: 7, title: "카운트 다운", platform: "programmers", problemId: "131129", algorithm: "DP" },
  { id: 169, difficulty: 7, title: "2차원 동전 뒤집기", platform: "programmers", problemId: "131703", algorithm: "비트마스킹, 완전탐색" },
  { id: 170, difficulty: 7, title: "공 이동 시뮬레이션", platform: "programmers", problemId: "87391", algorithm: "수학, 역추적" },
  { id: 171, difficulty: 7, title: "억억단을 외우자", platform: "programmers", problemId: "138475", algorithm: "수학" },
  { id: 172, difficulty: 7, title: "금과 은 운반하기", platform: "programmers", problemId: "86053", algorithm: "이진탐색, 수학" },
  { id: 173, difficulty: 7, title: "등대", platform: "programmers", problemId: "133500", algorithm: "트리, DP" },
  { id: 174, difficulty: 7, title: "숫자 타자 대회", platform: "programmers", problemId: "136797", algorithm: "DP" },
  { id: 175, difficulty: 7, title: "퍼즐 조각 채우기", platform: "programmers", problemId: "84021", algorithm: "DFS/BFS, 시뮬레이션" },
  { id: 176, difficulty: 7, title: "사라지는 발판", platform: "programmers", problemId: "92345", algorithm: "게임이론, 시뮬레이션" },
  { id: 177, difficulty: 7, title: "상담원 인원", platform: "programmers", problemId: "214288", algorithm: "이진탐색, 시뮬레이션" },
  { id: 178, difficulty: 7, title: "고고학 최고의 발견", platform: "programmers", problemId: "131702", algorithm: "완전탐색" },
  { id: 179, difficulty: 7, title: "아방가르드 타일링", platform: "programmers", problemId: "181186", algorithm: "DP" },
  { id: 180, difficulty: 7, title: "에어컨", platform: "programmers", problemId: "214289", algorithm: "DP" },

  // ========== 백준 레벨8 (181-218) ==========
  { id: 181, difficulty: 8, title: "Fly me to the Alpha Centauri", platform: "baekjoon", problemId: "1011", algorithm: "수학" },
  { id: 182, difficulty: 8, title: "터렛", platform: "baekjoon", problemId: "1002", algorithm: "수학" },
  { id: 183, difficulty: 8, title: "괄호", platform: "baekjoon", problemId: "9012", algorithm: "스택" },
  { id: 184, difficulty: 8, title: "균형잡힌 세상", platform: "baekjoon", problemId: "4949", algorithm: "스택" },
  { id: 185, difficulty: 8, title: "스택 수열", platform: "baekjoon", problemId: "1874", algorithm: "스택" },
  { id: 186, difficulty: 8, title: "회전하는 큐", platform: "baekjoon", problemId: "1021", algorithm: "큐, 덱" },
  { id: 187, difficulty: 8, title: "요세푸스 문제 0", platform: "baekjoon", problemId: "11866", algorithm: "큐" },
  { id: 188, difficulty: 8, title: "최대 힙", platform: "baekjoon", problemId: "11279", algorithm: "힙" },
  { id: 189, difficulty: 8, title: "최소 힙", platform: "baekjoon", problemId: "1927", algorithm: "힙" },
  { id: 190, difficulty: 8, title: "영화감독 숌", platform: "baekjoon", problemId: "1436", algorithm: "완전탐색" },
  { id: 191, difficulty: 8, title: "다리 놓기", platform: "baekjoon", problemId: "1010", algorithm: "DP, 조합" },
  { id: 192, difficulty: 8, title: "블랙잭", platform: "baekjoon", problemId: "2798", algorithm: "완전탐색" },
  { id: 193, difficulty: 8, title: "분해합", platform: "baekjoon", problemId: "2231", algorithm: "완전탐색" },
  { id: 194, difficulty: 8, title: "잃어버린 괄호", platform: "baekjoon", problemId: "1541", algorithm: "그리디" },
  { id: 195, difficulty: 8, title: "동전 0", platform: "baekjoon", problemId: "11047", algorithm: "그리디" },
  { id: 196, difficulty: 8, title: "ATM", platform: "baekjoon", problemId: "11399", algorithm: "그리디, 정렬" },
  { id: 197, difficulty: 8, title: "계단 오르기", platform: "baekjoon", problemId: "2579", algorithm: "DP" },
  { id: 198, difficulty: 8, title: "신나는 함수 실행", platform: "baekjoon", problemId: "9184", algorithm: "DP, 재귀" },
  { id: 199, difficulty: 8, title: "파도반 수열", platform: "baekjoon", problemId: "9461", algorithm: "DP" },
  { id: 200, difficulty: 8, title: "RGB거리", platform: "baekjoon", problemId: "1149", algorithm: "DP" },
  { id: 201, difficulty: 8, title: "정수 삼각형", platform: "baekjoon", problemId: "1932", algorithm: "DP" },
  { id: 202, difficulty: 8, title: "가장 긴 증가하는 부분 수열", platform: "baekjoon", problemId: "11053", algorithm: "DP" },
  { id: 203, difficulty: 8, title: "평범한 배낭", platform: "baekjoon", problemId: "12865", algorithm: "DP (배낭문제)" },
  { id: 204, difficulty: 8, title: "하노이 탑 이동 순서", platform: "baekjoon", problemId: "11729", algorithm: "재귀" },
  { id: 205, difficulty: 8, title: "좌표 정렬하기 2", platform: "baekjoon", problemId: "11651", algorithm: "정렬" },
  { id: 206, difficulty: 8, title: "나무 자르기", platform: "baekjoon", problemId: "2805", algorithm: "이진탐색" },
  { id: 207, difficulty: 8, title: "통계학", platform: "baekjoon", problemId: "2108", algorithm: "정렬, 수학" },
  { id: 208, difficulty: 8, title: "공유기 설치", platform: "baekjoon", problemId: "2110", algorithm: "이진탐색" },
  { id: 209, difficulty: 8, title: "K번째 수", platform: "baekjoon", problemId: "1300", algorithm: "이진탐색" },
  { id: 210, difficulty: 8, title: "가장 긴 증가하는 부분 수열 2", platform: "baekjoon", problemId: "12015", algorithm: "이진탐색, DP" },
  { id: 211, difficulty: 8, title: "DFS와 BFS", platform: "baekjoon", problemId: "1260", algorithm: "DFS/BFS" },
  { id: 212, difficulty: 8, title: "색종이 만들기", platform: "baekjoon", problemId: "2630", algorithm: "분할정복" },
  { id: 213, difficulty: 8, title: "N과 M (2)", platform: "baekjoon", problemId: "15650", algorithm: "백트래킹" },
  { id: 214, difficulty: 8, title: "N-Queen", platform: "baekjoon", problemId: "9663", algorithm: "백트래킹" },
  { id: 215, difficulty: 8, title: "바이러스", platform: "baekjoon", problemId: "2606", algorithm: "DFS/BFS" },
  { id: 216, difficulty: 8, title: "단지번호붙이기", platform: "baekjoon", problemId: "2667", algorithm: "DFS/BFS" },
  { id: 217, difficulty: 8, title: "토마토", platform: "baekjoon", problemId: "7576", algorithm: "BFS" },
  { id: 218, difficulty: 8, title: "유기농 배추", platform: "baekjoon", problemId: "1012", algorithm: "DFS/BFS" },

  // ========== 기초·입문 (219-441) ==========

  // 코딩테스트 입문 Lv.0 (219-318) - 100문제
  { id: 219, difficulty: 0, title: "두 수의 차 구하기", platform: "programmers", problemId: "120803", algorithm: "기초", category: "코딩테스트입문" },
  { id: 220, difficulty: 0, title: "숫자 비교하기", platform: "programmers", problemId: "120807", algorithm: "기초", category: "코딩테스트입문" },
  { id: 221, difficulty: 0, title: "나이 출력", platform: "programmers", problemId: "120820", algorithm: "기초", category: "코딩테스트입문" },
  { id: 222, difficulty: 0, title: "두 수의 나눗셈", platform: "programmers", problemId: "120806", algorithm: "기초", category: "코딩테스트입문" },
  { id: 223, difficulty: 0, title: "나머지 구하기", platform: "programmers", problemId: "120810", algorithm: "기초", category: "코딩테스트입문" },
  { id: 224, difficulty: 0, title: "두 수의 곱 구하기", platform: "programmers", problemId: "120804", algorithm: "기초", category: "코딩테스트입문" },
  { id: 225, difficulty: 0, title: "몫 구하기", platform: "programmers", problemId: "120805", algorithm: "기초", category: "코딩테스트입문" },
  { id: 226, difficulty: 0, title: "두 수의 합 구하기", platform: "programmers", problemId: "120802", algorithm: "기초", category: "코딩테스트입문" },
  { id: 227, difficulty: 0, title: "각도기", platform: "programmers", problemId: "120829", algorithm: "기초", category: "코딩테스트입문" },
  { id: 228, difficulty: 0, title: "양꼬치", platform: "programmers", problemId: "120830", algorithm: "기초", category: "코딩테스트입문" },
  { id: 229, difficulty: 0, title: "짝수의 합", platform: "programmers", problemId: "120831", algorithm: "기초", category: "코딩테스트입문" },
  { id: 230, difficulty: 0, title: "배열의 평균값", platform: "programmers", problemId: "120817", algorithm: "기초", category: "코딩테스트입문" },
  { id: 231, difficulty: 0, title: "배열 뒤집기", platform: "programmers", problemId: "120821", algorithm: "기초", category: "코딩테스트입문" },
  { id: 232, difficulty: 0, title: "뒤집힌 문자열", platform: "programmers", problemId: "120822", algorithm: "기초", category: "코딩테스트입문" },
  { id: 233, difficulty: 0, title: "편지", platform: "programmers", problemId: "120898", algorithm: "기초", category: "코딩테스트입문" },
  { id: 234, difficulty: 0, title: "피자 나눠 먹기 (1)", platform: "programmers", problemId: "120814", algorithm: "기초", category: "코딩테스트입문" },
  { id: 235, difficulty: 0, title: "세균 증식", platform: "programmers", problemId: "120910", algorithm: "기초", category: "코딩테스트입문" },
  { id: 236, difficulty: 0, title: "최댓값 만들기(1)", platform: "programmers", problemId: "120847", algorithm: "기초", category: "코딩테스트입문" },
  { id: 237, difficulty: 0, title: "머쓱이보다 키 큰 사람", platform: "programmers", problemId: "120585", algorithm: "기초", category: "코딩테스트입문" },
  { id: 238, difficulty: 0, title: "삼각형의 완성조건 (1)", platform: "programmers", problemId: "120889", algorithm: "기초", category: "코딩테스트입문" },
  { id: 239, difficulty: 0, title: "배열 자르기", platform: "programmers", problemId: "120833", algorithm: "기초", category: "코딩테스트입문" },
  { id: 240, difficulty: 0, title: "피자 나눠 먹기 (3)", platform: "programmers", problemId: "120816", algorithm: "기초", category: "코딩테스트입문" },
  { id: 241, difficulty: 0, title: "점의 위치 구하기", platform: "programmers", problemId: "120841", algorithm: "기초", category: "코딩테스트입문" },
  { id: 242, difficulty: 0, title: "배열의 유사도", platform: "programmers", problemId: "120903", algorithm: "기초", category: "코딩테스트입문" },
  { id: 243, difficulty: 0, title: "순서쌍의 개수", platform: "programmers", problemId: "120836", algorithm: "기초", category: "코딩테스트입문" },
  { id: 244, difficulty: 0, title: "n의 배수 고르기", platform: "programmers", problemId: "120905", algorithm: "기초", category: "코딩테스트입문" },
  { id: 245, difficulty: 0, title: "배열 원소의 길이", platform: "programmers", problemId: "120854", algorithm: "기초", category: "코딩테스트입문" },
  { id: 246, difficulty: 0, title: "아이스 아메리카노", platform: "programmers", problemId: "120819", algorithm: "기초", category: "코딩테스트입문" },
  { id: 247, difficulty: 0, title: "문자열안에 문자열", platform: "programmers", problemId: "120908", algorithm: "기초", category: "코딩테스트입문" },
  { id: 248, difficulty: 0, title: "문자 반복 출력하기", platform: "programmers", problemId: "120825", algorithm: "기초", category: "코딩테스트입문" },
  { id: 249, difficulty: 0, title: "제곱수 판별하기", platform: "programmers", problemId: "120909", algorithm: "기초", category: "코딩테스트입문" },
  { id: 250, difficulty: 0, title: "특정 문자 제거하기", platform: "programmers", problemId: "120826", algorithm: "기초", category: "코딩테스트입문" },
  { id: 251, difficulty: 0, title: "모음 제거", platform: "programmers", problemId: "120849", algorithm: "기초", category: "코딩테스트입문" },
  { id: 252, difficulty: 0, title: "짝수 홀수 개수", platform: "programmers", problemId: "120824", algorithm: "기초", category: "코딩테스트입문" },
  { id: 253, difficulty: 0, title: "자릿수 더하기", platform: "programmers", problemId: "120906", algorithm: "기초", category: "코딩테스트입문" },
  { id: 254, difficulty: 0, title: "숨어있는 숫자의 덧셈 (1)", platform: "programmers", problemId: "120851", algorithm: "기초", category: "코딩테스트입문" },
  { id: 255, difficulty: 0, title: "배열 두 배 만들기", platform: "programmers", problemId: "120809", algorithm: "기초", category: "코딩테스트입문" },
  { id: 256, difficulty: 0, title: "중복된 숫자 개수", platform: "programmers", problemId: "120583", algorithm: "기초", category: "코딩테스트입문" },
  { id: 257, difficulty: 0, title: "중앙값 구하기", platform: "programmers", problemId: "120811", algorithm: "기초", category: "코딩테스트입문" },
  { id: 258, difficulty: 0, title: "짝수는 싫어요", platform: "programmers", problemId: "120813", algorithm: "기초", category: "코딩테스트입문" },
  { id: 259, difficulty: 0, title: "옷가게 할인 받기", platform: "programmers", problemId: "120818", algorithm: "기초", category: "코딩테스트입문" },
  { id: 260, difficulty: 0, title: "직각삼각형 출력하기", platform: "programmers", problemId: "120823", algorithm: "기초", category: "코딩테스트입문" },
  { id: 261, difficulty: 0, title: "개미 군단", platform: "programmers", problemId: "120837", algorithm: "기초", category: "코딩테스트입문" },
  { id: 262, difficulty: 0, title: "가위 바위 보", platform: "programmers", problemId: "120839", algorithm: "기초", category: "코딩테스트입문" },
  { id: 263, difficulty: 0, title: "주사위의 개수", platform: "programmers", problemId: "120845", algorithm: "기초", category: "코딩테스트입문" },
  { id: 264, difficulty: 0, title: "문자열 정렬하기 (1)", platform: "programmers", problemId: "120850", algorithm: "기초", category: "코딩테스트입문" },
  { id: 265, difficulty: 0, title: "최댓값 만들기 (2)", platform: "programmers", problemId: "120862", algorithm: "기초", category: "코딩테스트입문" },
  { id: 266, difficulty: 0, title: "암호 해독", platform: "programmers", problemId: "120892", algorithm: "기초", category: "코딩테스트입문" },
  { id: 267, difficulty: 0, title: "인덱스 바꾸기", platform: "programmers", problemId: "120895", algorithm: "기초", category: "코딩테스트입문" },
  { id: 268, difficulty: 0, title: "약수 구하기", platform: "programmers", problemId: "120897", algorithm: "기초", category: "코딩테스트입문" },
  { id: 269, difficulty: 0, title: "가장 큰 수 찾기", platform: "programmers", problemId: "120899", algorithm: "기초", category: "코딩테스트입문" },
  { id: 270, difficulty: 0, title: "문자열 정렬하기 (2)", platform: "programmers", problemId: "120911", algorithm: "기초", category: "코딩테스트입문" },
  { id: 271, difficulty: 0, title: "숫자 찾기", platform: "programmers", problemId: "120904", algorithm: "기초", category: "코딩테스트입문" },
  { id: 272, difficulty: 0, title: "대문자와 소문자", platform: "programmers", problemId: "120893", algorithm: "기초", category: "코딩테스트입문" },
  { id: 273, difficulty: 0, title: "피자 나눠 먹기 (2)", platform: "programmers", problemId: "120815", algorithm: "기초", category: "코딩테스트입문" },
  { id: 274, difficulty: 0, title: "외계행성의 나이", platform: "programmers", problemId: "120834", algorithm: "기초", category: "코딩테스트입문" },
  { id: 275, difficulty: 0, title: "배열 회전시키기", platform: "programmers", problemId: "120844", algorithm: "기초", category: "코딩테스트입문" },
  { id: 276, difficulty: 0, title: "369게임", platform: "programmers", problemId: "120891", algorithm: "기초", category: "코딩테스트입문" },
  { id: 277, difficulty: 0, title: "합성수 찾기", platform: "programmers", problemId: "120846", algorithm: "기초", category: "코딩테스트입문" },
  { id: 278, difficulty: 0, title: "중복된 문자 제거", platform: "programmers", problemId: "120888", algorithm: "기초", category: "코딩테스트입문" },
  { id: 279, difficulty: 0, title: "2차원으로 만들기", platform: "programmers", problemId: "120842", algorithm: "기초", category: "코딩테스트입문" },
  { id: 280, difficulty: 0, title: "모스부호 (1)", platform: "programmers", problemId: "120838", algorithm: "기초", category: "코딩테스트입문" },
  { id: 281, difficulty: 0, title: "A로 B 만들기", platform: "programmers", problemId: "120886", algorithm: "기초", category: "코딩테스트입문" },
  { id: 282, difficulty: 0, title: "k의 개수", platform: "programmers", problemId: "120887", algorithm: "기초", category: "코딩테스트입문" },
  { id: 283, difficulty: 0, title: "한 번만 등장한 문자", platform: "programmers", problemId: "120896", algorithm: "기초", category: "코딩테스트입문" },
  { id: 284, difficulty: 0, title: "숨어있는 숫자의 덧셈 (2)", platform: "programmers", problemId: "120864", algorithm: "기초", category: "코딩테스트입문" },
  { id: 285, difficulty: 0, title: "7의 개수", platform: "programmers", problemId: "120912", algorithm: "기초", category: "코딩테스트입문" },
  { id: 286, difficulty: 0, title: "진료순서 정하기", platform: "programmers", problemId: "120835", algorithm: "기초", category: "코딩테스트입문" },
  { id: 287, difficulty: 0, title: "가까운 수", platform: "programmers", problemId: "120890", algorithm: "기초", category: "코딩테스트입문" },
  { id: 288, difficulty: 0, title: "팩토리얼", platform: "programmers", problemId: "120848", algorithm: "기초", category: "코딩테스트입문" },
  { id: 289, difficulty: 0, title: "잘라서 배열로 저장하기", platform: "programmers", problemId: "120913", algorithm: "기초", category: "코딩테스트입문" },
  { id: 290, difficulty: 0, title: "컨트롤 제트", platform: "programmers", problemId: "120853", algorithm: "기초", category: "코딩테스트입문" },
  { id: 291, difficulty: 0, title: "소인수분해", platform: "programmers", problemId: "120852", algorithm: "기초", category: "코딩테스트입문" },
  { id: 292, difficulty: 0, title: "문자열 계산하기", platform: "programmers", problemId: "120902", algorithm: "기초", category: "코딩테스트입문" },
  { id: 293, difficulty: 0, title: "공 던지기", platform: "programmers", problemId: "120843", algorithm: "기초", category: "코딩테스트입문" },
  { id: 294, difficulty: 0, title: "이진수 더하기", platform: "programmers", problemId: "120885", algorithm: "기초", category: "코딩테스트입문" },
  { id: 295, difficulty: 0, title: "영어가 싫어요", platform: "programmers", problemId: "120894", algorithm: "기초", category: "코딩테스트입문" },
  { id: 296, difficulty: 0, title: "삼각형의 완성조건 (2)", platform: "programmers", problemId: "120868", algorithm: "기초", category: "코딩테스트입문" },
  { id: 297, difficulty: 0, title: "구슬을 나누는 경우의 수", platform: "programmers", problemId: "120840", algorithm: "기초", category: "코딩테스트입문" },
  { id: 298, difficulty: 0, title: "캐릭터의 좌표", platform: "programmers", problemId: "120861", algorithm: "기초", category: "코딩테스트입문" },
  { id: 299, difficulty: 0, title: "종이 자르기", platform: "programmers", problemId: "120922", algorithm: "기초", category: "코딩테스트입문" },
  { id: 300, difficulty: 0, title: "외계어 사전", platform: "programmers", problemId: "120869", algorithm: "기초", category: "코딩테스트입문" },
  { id: 301, difficulty: 0, title: "로그인 성공?", platform: "programmers", problemId: "120883", algorithm: "기초", category: "코딩테스트입문" },
  { id: 302, difficulty: 0, title: "직사각형 넓이 구하기", platform: "programmers", problemId: "120860", algorithm: "기초", category: "코딩테스트입문" },
  { id: 303, difficulty: 0, title: "치킨 쿠폰", platform: "programmers", problemId: "120884", algorithm: "기초", category: "코딩테스트입문" },
  { id: 304, difficulty: 0, title: "등수 매기기", platform: "programmers", problemId: "120882", algorithm: "기초", category: "코딩테스트입문" },
  { id: 305, difficulty: 0, title: "저주의 숫자 3", platform: "programmers", problemId: "120871", algorithm: "기초", category: "코딩테스트입문" },
  { id: 306, difficulty: 0, title: "문자열 밀기", platform: "programmers", problemId: "120921", algorithm: "기초", category: "코딩테스트입문" },
  { id: 307, difficulty: 0, title: "유한소수 판별하기", platform: "programmers", problemId: "120878", algorithm: "기초", category: "코딩테스트입문" },
  { id: 308, difficulty: 0, title: "특이한 정렬", platform: "programmers", problemId: "120880", algorithm: "기초", category: "코딩테스트입문" },
  { id: 309, difficulty: 0, title: "다항식 더하기", platform: "programmers", problemId: "120863", algorithm: "기초", category: "코딩테스트입문" },
  { id: 310, difficulty: 0, title: "최빈값 구하기", platform: "programmers", problemId: "120812", algorithm: "기초", category: "코딩테스트입문" },
  { id: 311, difficulty: 0, title: "OX퀴즈", platform: "programmers", problemId: "120907", algorithm: "기초", category: "코딩테스트입문" },
  { id: 312, difficulty: 0, title: "다음에 올 숫자", platform: "programmers", problemId: "120924", algorithm: "기초", category: "코딩테스트입문" },
  { id: 313, difficulty: 0, title: "연속된 수의 합", platform: "programmers", problemId: "120923", algorithm: "기초", category: "코딩테스트입문" },
  { id: 314, difficulty: 0, title: "안전지대", platform: "programmers", problemId: "120866", algorithm: "기초", category: "코딩테스트입문" },
  { id: 315, difficulty: 0, title: "분수의 덧셈", platform: "programmers", problemId: "120808", algorithm: "기초", category: "코딩테스트입문" },
  { id: 316, difficulty: 0, title: "겹치는 선분의 길이", platform: "programmers", problemId: "120876", algorithm: "기초", category: "코딩테스트입문" },
  { id: 317, difficulty: 0, title: "평행", platform: "programmers", problemId: "120875", algorithm: "기초", category: "코딩테스트입문" },
  { id: 318, difficulty: 0, title: "옹알이 (1)", platform: "programmers", problemId: "120956", algorithm: "기초", category: "코딩테스트입문" },

  // 코딩 기초 트레이닝 Lv.0 (319-441) - 123문제
  { id: 319, difficulty: 0, title: "홀짝 구분하기", platform: "programmers", problemId: "181944", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 320, difficulty: 0, title: "문자 리스트를 문자열로 변환하기", platform: "programmers", problemId: "181941", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 321, difficulty: 0, title: "홀짝에 따라 다른 값 반환하기", platform: "programmers", problemId: "181935", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 322, difficulty: 0, title: "대문자로 바꾸기", platform: "programmers", problemId: "181877", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 323, difficulty: 0, title: "문자열 붙여서 출력하기", platform: "programmers", problemId: "181946", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 324, difficulty: 0, title: "flag에 따라 다른 값 반환하기", platform: "programmers", problemId: "181933", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 325, difficulty: 0, title: "원소들의 곱과 합", platform: "programmers", problemId: "181929", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 326, difficulty: 0, title: "첫 번째로 나오는 음수", platform: "programmers", problemId: "181896", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 327, difficulty: 0, title: "더 크게 합치기", platform: "programmers", problemId: "181939", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 328, difficulty: 0, title: "문자열 곱하기", platform: "programmers", problemId: "181940", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 329, difficulty: 0, title: "공배수", platform: "programmers", problemId: "181936", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 330, difficulty: 0, title: "n의 배수", platform: "programmers", problemId: "181937", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 331, difficulty: 0, title: "두 수의 연산값 비교하기", platform: "programmers", problemId: "181938", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 332, difficulty: 0, title: "카운트 업", platform: "programmers", problemId: "181920", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 333, difficulty: 0, title: "n 번째 원소부터", platform: "programmers", problemId: "181892", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 334, difficulty: 0, title: "문자열의 앞의 n글자", platform: "programmers", problemId: "181907", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 335, difficulty: 0, title: "문자열의 뒤의 n글자", platform: "programmers", problemId: "181910", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 336, difficulty: 0, title: "이어 붙인 수", platform: "programmers", problemId: "181928", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 337, difficulty: 0, title: "n 번째 원소까지", platform: "programmers", problemId: "181889", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 338, difficulty: 0, title: "n개 간격의 원소들", platform: "programmers", problemId: "181888", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 339, difficulty: 0, title: "글자 이어 붙여 문자열 만들기", platform: "programmers", problemId: "181915", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 340, difficulty: 0, title: "콜라츠 수열 만들기", platform: "programmers", problemId: "181919", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 341, difficulty: 0, title: "주사위 게임 2", platform: "programmers", problemId: "181930", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 342, difficulty: 0, title: "문자열 돌리기", platform: "programmers", problemId: "181945", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 343, difficulty: 0, title: "덧셈식 출력하기", platform: "programmers", problemId: "181947", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 344, difficulty: 0, title: "특정한 문자를 대문자로 바꾸기", platform: "programmers", problemId: "181873", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 345, difficulty: 0, title: "조건에 맞게 수열 변환하기 3", platform: "programmers", problemId: "181835", algorithm: "반복문 활용", category: "코딩기초트레이닝" },
  { id: 346, difficulty: 0, title: "l로 만들기", platform: "programmers", problemId: "181834", algorithm: "반복문 활용", category: "코딩기초트레이닝" },
  { id: 347, difficulty: 0, title: "정수 부분", platform: "programmers", problemId: "181850", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 348, difficulty: 0, title: "문자열 바꿔서 찾기", platform: "programmers", problemId: "181864", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 349, difficulty: 0, title: "정수 찾기", platform: "programmers", problemId: "181840", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 350, difficulty: 0, title: "배열의 원소 삭제하기", platform: "programmers", problemId: "181844", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 351, difficulty: 0, title: "꼬리 문자열", platform: "programmers", problemId: "181841", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 352, difficulty: 0, title: "0 떼기", platform: "programmers", problemId: "181847", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 353, difficulty: 0, title: "부분 문자열", platform: "programmers", problemId: "181842", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 354, difficulty: 0, title: "부분 문자열인지 확인하기", platform: "programmers", problemId: "181843", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 355, difficulty: 0, title: "문자열로 변환", platform: "programmers", problemId: "181845", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 356, difficulty: 0, title: "뒤에서 5등 위로", platform: "programmers", problemId: "181852", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 357, difficulty: 0, title: "문자열 정수의 합", platform: "programmers", problemId: "181849", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 358, difficulty: 0, title: "문자열을 정수로 변환하기", platform: "programmers", problemId: "181848", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 359, difficulty: 0, title: "뒤에서 5등까지", platform: "programmers", problemId: "181853", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 360, difficulty: 0, title: "배열의 길이에 따라 다른 연산하기", platform: "programmers", problemId: "181854", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 361, difficulty: 0, title: "배열 비교하기", platform: "programmers", problemId: "181856", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 362, difficulty: 0, title: "주사위 게임 1", platform: "programmers", problemId: "181839", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 363, difficulty: 0, title: "ad 제거하기", platform: "programmers", problemId: "181870", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 364, difficulty: 0, title: "배열의 원소만큼 추가하기", platform: "programmers", problemId: "181861", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 365, difficulty: 0, title: "x 사이의 개수", platform: "programmers", problemId: "181867", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 366, difficulty: 0, title: "홀수 vs 짝수", platform: "programmers", problemId: "181887", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 367, difficulty: 0, title: "공백으로 구분하기 2", platform: "programmers", problemId: "181868", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 368, difficulty: 0, title: "rny_string", platform: "programmers", problemId: "181863", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 369, difficulty: 0, title: "공백으로 구분하기 1", platform: "programmers", problemId: "181869", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 370, difficulty: 0, title: "배열에서 문자열 대소문자 변환하기", platform: "programmers", problemId: "181875", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 371, difficulty: 0, title: "간단한 식 계산하기", platform: "programmers", problemId: "181865", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 372, difficulty: 0, title: "소문자로 바꾸기", platform: "programmers", problemId: "181876", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 373, difficulty: 0, title: "가까운 1 찾기", platform: "programmers", problemId: "181898", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 374, difficulty: 0, title: "원하는 문자열 찾기", platform: "programmers", problemId: "181878", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 375, difficulty: 0, title: "배열 만들기 3", platform: "programmers", problemId: "181895", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 376, difficulty: 0, title: "길이에 따른 연산", platform: "programmers", problemId: "181879", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 377, difficulty: 0, title: "조건에 맞게 수열 변환하기 1", platform: "programmers", problemId: "181882", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 378, difficulty: 0, title: "할 일 목록", platform: "programmers", problemId: "181885", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 379, difficulty: 0, title: "9로 나눈 나머지", platform: "programmers", problemId: "181914", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 380, difficulty: 0, title: "n보다 커질 때까지 더하기", platform: "programmers", problemId: "181884", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 381, difficulty: 0, title: "순서 바꾸기", platform: "programmers", problemId: "181891", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 382, difficulty: 0, title: "A 강조하기", platform: "programmers", problemId: "181874", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 383, difficulty: 0, title: "5명씩", platform: "programmers", problemId: "181886", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 384, difficulty: 0, title: "배열 만들기 1", platform: "programmers", problemId: "181901", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 385, difficulty: 0, title: "부분 문자열 이어 붙여 문자열 만들기", platform: "programmers", problemId: "181911", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 386, difficulty: 0, title: "카운트 다운", platform: "programmers", problemId: "181899", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 387, difficulty: 0, title: "접미사 배열", platform: "programmers", problemId: "181909", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 388, difficulty: 0, title: "수 조작하기 2", platform: "programmers", problemId: "181925", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 389, difficulty: 0, title: "특별한 이차원 배열 2", platform: "programmers", problemId: "181831", algorithm: "이차원 리스트(배열)", category: "코딩기초트레이닝" },
  { id: 390, difficulty: 0, title: "특별한 이차원 배열 1", platform: "programmers", problemId: "181833", algorithm: "이차원 리스트(배열)", category: "코딩기초트레이닝" },
  { id: 391, difficulty: 0, title: "문자열 잘라서 정렬하기", platform: "programmers", problemId: "181866", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 392, difficulty: 0, title: "마지막 두 원소", platform: "programmers", problemId: "181927", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 393, difficulty: 0, title: "접미사인지 확인하기", platform: "programmers", problemId: "181908", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 394, difficulty: 0, title: "수 조작하기 1", platform: "programmers", problemId: "181926", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 395, difficulty: 0, title: "세로 읽기", platform: "programmers", problemId: "181904", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 396, difficulty: 0, title: "이차원 배열 대각선 순회하기", platform: "programmers", problemId: "181829", algorithm: "이차원 리스트(배열)", category: "코딩기초트레이닝" },
  { id: 397, difficulty: 0, title: "문자열 섞기", platform: "programmers", problemId: "181942", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 398, difficulty: 0, title: "등차수열의 특정한 항만 더하기", platform: "programmers", problemId: "181931", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 399, difficulty: 0, title: "날짜 비교하기", platform: "programmers", problemId: "181838", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 400, difficulty: 0, title: "글자 지우기", platform: "programmers", problemId: "181900", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 401, difficulty: 0, title: "빈 배열에 추가, 삭제하기", platform: "programmers", problemId: "181860", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 402, difficulty: 0, title: "수열과 구간 쿼리 1", platform: "programmers", problemId: "181883", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 403, difficulty: 0, title: "배열 만들기 5", platform: "programmers", problemId: "181912", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 404, difficulty: 0, title: "1로 만들기", platform: "programmers", problemId: "181880", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 405, difficulty: 0, title: "문자열 뒤집기", platform: "programmers", problemId: "181905", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 406, difficulty: 0, title: "특정 문자열로 끝나는 가장 긴 부분 문자열 찾기", platform: "programmers", problemId: "181872", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 407, difficulty: 0, title: "문자열이 몇 번 등장하는지 세기", platform: "programmers", problemId: "181871", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 408, difficulty: 0, title: "수열과 구간 쿼리 3", platform: "programmers", problemId: "181924", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 409, difficulty: 0, title: "배열의 길이를 2의 거듭제곱으로 만들기", platform: "programmers", problemId: "181857", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 410, difficulty: 0, title: "문자열 묶기", platform: "programmers", problemId: "181855", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 411, difficulty: 0, title: "세 개의 구분자", platform: "programmers", problemId: "181862", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 412, difficulty: 0, title: "2의 영역", platform: "programmers", problemId: "181894", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 413, difficulty: 0, title: "간단한 논리 연산", platform: "programmers", problemId: "181917", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 414, difficulty: 0, title: "문자열 반복해서 출력하기", platform: "programmers", problemId: "181950", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 415, difficulty: 0, title: "리스트 자르기", platform: "programmers", problemId: "181897", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 416, difficulty: 0, title: "수열과 구간 쿼리 4", platform: "programmers", problemId: "181922", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 417, difficulty: 0, title: "qr code", platform: "programmers", problemId: "181903", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 418, difficulty: 0, title: "조건에 맞게 수열 변환하기 2", platform: "programmers", problemId: "181881", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 419, difficulty: 0, title: "특수문자 출력하기", platform: "programmers", problemId: "181948", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 420, difficulty: 0, title: "커피 심부름", platform: "programmers", problemId: "181837", algorithm: "조건문 활용", category: "코딩기초트레이닝" },
  { id: 421, difficulty: 0, title: "왼쪽 오른쪽", platform: "programmers", problemId: "181890", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 422, difficulty: 0, title: "배열 만들기 6", platform: "programmers", problemId: "181859", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 423, difficulty: 0, title: "문자 개수 세기", platform: "programmers", problemId: "181902", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 424, difficulty: 0, title: "조건 문자열", platform: "programmers", problemId: "181934", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 425, difficulty: 0, title: "배열 만들기 4", platform: "programmers", problemId: "181918", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 426, difficulty: 0, title: "문자열 여러 번 뒤집기", platform: "programmers", problemId: "181913", algorithm: "문자열", category: "코딩기초트레이닝" },
  { id: 427, difficulty: 0, title: "두 수의 합", platform: "programmers", problemId: "181846", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 428, difficulty: 0, title: "수열과 구간 쿼리 2", platform: "programmers", problemId: "181923", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 429, difficulty: 0, title: "무작위로 K개의 수 뽑기", platform: "programmers", problemId: "181858", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 430, difficulty: 0, title: "그림 확대", platform: "programmers", problemId: "181836", algorithm: "반복문 활용", category: "코딩기초트레이닝" },
  { id: 431, difficulty: 0, title: "a와 b 출력하기", platform: "programmers", problemId: "181951", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 432, difficulty: 0, title: "문자열 겹쳐쓰기", platform: "programmers", problemId: "181943", algorithm: "연산", category: "코딩기초트레이닝" },
  { id: 433, difficulty: 0, title: "정사각형으로 만들기", platform: "programmers", problemId: "181830", algorithm: "이차원 리스트(배열)", category: "코딩기초트레이닝" },
  { id: 434, difficulty: 0, title: "대소문자 바꿔서 출력하기", platform: "programmers", problemId: "181949", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 435, difficulty: 0, title: "전국 대회 선발 고사", platform: "programmers", problemId: "181851", algorithm: "함수(메서드)", category: "코딩기초트레이닝" },
  { id: 436, difficulty: 0, title: "배열 만들기 2", platform: "programmers", problemId: "181921", algorithm: "반복문", category: "코딩기초트레이닝" },
  { id: 437, difficulty: 0, title: "코드 처리하기", platform: "programmers", problemId: "181932", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 438, difficulty: 0, title: "배열 조각하기", platform: "programmers", problemId: "181893", algorithm: "리스트(배열)", category: "코딩기초트레이닝" },
  { id: 439, difficulty: 0, title: "문자열 출력하기", platform: "programmers", problemId: "181952", algorithm: "출력", category: "코딩기초트레이닝" },
  { id: 440, difficulty: 0, title: "주사위 게임 3", platform: "programmers", problemId: "181916", algorithm: "조건문", category: "코딩기초트레이닝" },
  { id: 441, difficulty: 0, title: "정수를 나선형으로 배치하기", platform: "programmers", problemId: "181832", algorithm: "이차원 리스트(배열)", category: "코딩기초트레이닝" }
];

// 난이도별 정보
const DIFFICULTY_INFO = {
  0: { name: "L0", display: "🌱", label: "기초·입문", folder: "L0_기초입문" },
  1: { name: "L1", display: "⭐", label: "입문", folder: "L1_입문" },
  2: { name: "L2", display: "⭐⭐", label: "기초", folder: "L2_기초" },
  3: { name: "L3", display: "⭐⭐⭐", label: "중급", folder: "L3_중급" },
  4: { name: "L4", display: "⭐⭐⭐⭐", label: "중상", folder: "L4_중상" },
  5: { name: "L5", display: "⭐⭐⭐⭐⭐", label: "고급", folder: "L5_고급" },
  7: { name: "레벨7", display: "🔥", label: "챌린지", folder: "L7_챌린지" },
  8: { name: "레벨8", display: "💎", label: "백준", folder: "L8_백준" }
};

// 플랫폼별 URL 생성 함수
function getProblemUrl(problem) {
  if (problem.platform === "programmers") {
    return `https://school.programmers.co.kr/learn/courses/30/lessons/${problem.problemId}`;
  } else if (problem.platform === "baekjoon") {
    return `https://www.acmicpc.net/problem/${problem.problemId}`;
  }
  return "#";
}

// 플랫폼별 문제 필터링
function getProblemsByPlatform(platform) {
  return PROBLEMS.filter(p => p.platform === platform);
}

// 난이도별 문제 필터링
function getProblemsByDifficulty(difficulty) {
  return PROBLEMS.filter(p => p.difficulty === difficulty);
}

// 문제 ID로 문제 찾기
function getProblemById(id) {
  return PROBLEMS.find(p => p.id === id);
}

// problemId로 문제 찾기 (content script에서 사용)
function getProblemByProblemId(problemId, platform) {
  return PROBLEMS.find(p => p.problemId === problemId && p.platform === platform);
}

// GitHub 저장 경로 생성
function getGitHubPath(problem) {
  const diffInfo = DIFFICULTY_INFO[problem.difficulty];
  const platformFolder = problem.platform === "programmers" ? "programmers" : "baekjoon";
  const fileName = `${String(problem.id).padStart(3, '0')}_${problem.title.replace(/[^가-힣a-zA-Z0-9]/g, '_')}.py`;

  // L0 (기초·입문) 문제는 카테고리별 하위 폴더 사용
  if (problem.difficulty === 0 && problem.category) {
    const subFolder = problem.category === '코딩테스트입문' ? '입문' : '기초트레이닝';
    return `${platformFolder}/${diffInfo.folder}/${subFolder}/${fileName}`;
  }

  return `${platformFolder}/${diffInfo.folder}/${fileName}`;
}
